// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQtnkbhxfx-_L8TARCZ_JdfI5sm9idWPc',
    appId: '1:299051492096:android:cb4d724b03b8b9baa289e5',
    messagingSenderId: '299051492096',
    projectId: 'school-violence-d8038',
    databaseURL: 'https://school-violence-d8038-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'school-violence-d8038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhs7QnkKtmr8ycUMDS-21TJpugij7XPnk',
    appId: '1:299051492096:ios:7544fdeee4ffdf53a289e5',
    messagingSenderId: '299051492096',
    projectId: 'school-violence-d8038',
    databaseURL: 'https://school-violence-d8038-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'school-violence-d8038.appspot.com',
    androidClientId: '299051492096-471dvugn7ds6jrtenu2iivf785fta4br.apps.googleusercontent.com',
    iosClientId: '299051492096-1igc2fo4rajtd7ebuntf4g73cgs5s9fj.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolViolenceApp',
  );
}
